### ISSUE TITLE
Expandable view height issue

### ISSUE THREAD

**Issue by dduvedi** [sourabhgupta811/ExpandableRecyclerView#1]
If we want to show view in more than one lines, animation of expansion isn't working smooth.

**Comment by dduvedi** [comment]
I have fixed the issue, but cannot create and push branch

**Comment by adeel-tariq** [comment]
> I have fixed the issue, but cannot create and push branch

@dduvedi Hi,
im trying to show text in multiple lines, and like u said its not very smooth and also only first line of text is shown.
Can u tell me how did u solve it?

Thank You.

**Comment by sourabhgupta811** [comment]
Hi @adeel-tariq 
The basic idea is to precalculate the dimension when collapsing or expanding. So, in case you want to show multiple lines of text, one solution can be to measure the TextView size by calculating it with StaticLayout and expand to that size.

**Comment by sourabhgupta811** [comment]
This sample has been deprecated.
Please use [ExpandableLayout](https://github.com/sourabhgupta811/ExpandableLayout)
